// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"path"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/coze-dev/coze-studio/backend/api/handler/coze"
	"github.com/coze-dev/coze-studio/backend/pkg/logs"
)

func main() {
	// 为 Windows 平台提供简化的启动方案
	h := server.Default(server.WithHostPorts("0.0.0.0:8888"))

	// 不注册任何中间件，直接注册测试路由

	// Register third-party login endpoint
	h.GET("/api/auth/third_login", coze.PassportThirdLoginGet)

	// Register connect session endpoint
	h.GET("/api/open/connect/session", coze.PassportConnectSessionGet)

	// Test route
	h.GET("/test", func(c context.Context, ctx *app.RequestContext) {
		ctx.String(200, "Test route works!")
	})

	// 不注册其他 API 路由，避免中间件拦截
	// if runtime.GOOS != "windows" {
	// 	// Register other API routes
	// 	router.GeneratedRegister(h)
	// }

	// Register static file routes
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warnf("[main] Failed to get current working directory: %v", err)
		cwd = os.Getenv("PWD")
	}

	staticFile := path.Join(cwd, "resources/static/index.html")

	h.Static("/static", path.Join(cwd, "/resources/static"))
	h.StaticFile("/favicon.png", "./resources/static/favicon.png")

	h.StaticFS("/admin", &app.FS{
		Root:               path.Join(cwd, "/resources/conf"),
		GenerateIndexPages: true,
		IndexNames:         []string{"index.html"},
	})

	type data struct {
		Code int32  `json:"code"`
		Msg  string `json:"msg"`
	}

	h.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		path := string(ctx.GetRequest().URI().Path())
		if strings.HasPrefix(path, "/api/") ||
			strings.HasPrefix(path, "/v1/") ||
			strings.HasPrefix(path, "/v3/") {
			ctx.JSON(404, data{
				Code: 404,
				Msg:  "not found",
			})
			return
		}

		// index page will show 404 error
		ctx.File(staticFile)
	})

	h.Spin()
}
