// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/coze-dev/coze-studio/backend/api/handler"
	coze "github.com/coze-dev/coze-studio/backend/api/handler/coze"
	"github.com/coze-dev/coze-studio/backend/api/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// Register third-party login endpoint
	r.GET("/api/auth/third_login", coze.PassportThirdLoginGet)

	// your code ...
}
