# 由 default.conf 的 server 块 include；勿单独作为 conf.d 顶层加载（无 server 上下文）

# Static resources
location / {
    root   /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
    index  index.html index.htm;
    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;

    etag on;
    if_modified_since exact;
    add_header Cache-Control "no-cache";
}

# API proxy
location ~ ^/(api|v[1-3]|admin)(/|$) {
    proxy_pass http://coze-server:8888;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 600s;

    proxy_ssl_protocols TLSv1.2 TLSv1.3;
    proxy_ssl_verify off;

    sub_filter ':8889' ':8888/local_storage';
    sub_filter 'minio:9000' '$http_host/local_storage';
    sub_filter_once off;
    sub_filter_types 'application/json' 'text/event-stream';
}

location /local_storage/ {
    if ($args ~* "(^|.*&)x-wf-file_name=[^&]*(&.*|$)") {
        set $args $1$2;
    }
    if ($args ~* "^x-wf-file_name=[^&]*$") {
        set $args "";
    }

    rewrite ^/local_storage/(.*)$ /$1 break;
    set $minio_pass http://minio:9000;
    proxy_pass $minio_pass;
    proxy_set_header Host minio:9000;
}
